on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: triagecontainerregistry.azurecr.io
        username: ${{ secrets.acr_triagecontainerregistry_username }}
        password: ${{ secrets.acr_triagecontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
        docker push triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_triagekubernetescluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep triagekubernetescluster043f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace triagekubernetescluster043f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: triagekubernetescluster043f
        container-registry-url: triagecontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_triagecontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_triagecontainerregistry_password }}
        secret-name: triagekuberndockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: triagekubernetescluster043f
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
        imagepullsecrets: |
          triagekuberndockerauth