on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n triagecontainerregistry -g triagecontainerregistry8fec-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n triagecontainerregistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n triagecontainerregistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n triagecontainerregistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: triagecontainerregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
        docker push triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_triagekubernetescluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep triagekubernetesclusterefe5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace triagekubernetesclusterefe5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: triagekubernetesclusterefe5
        container-registry-url: triagecontainerregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: triagekuberndockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: triagekubernetesclusterefe5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          triagecontainerregistry.azurecr.io/triagekubernetescluster:${{ github.sha }}
        imagepullsecrets: |
          triagekuberndockerauth